spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:tienda_ropa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: never

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

app:
  version: ${APP_VERSION:1.0.0-local}
  name: Tienda Ropa API